Ex_Files_ASPNET_CoreMVC/Ex_Files_ASPNET_CoreMVC/Exercise Files/Ch03/03_08_End/src/ExploreCalifornia/Models/FormattingService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExploreCalifornia.Models
{
    public class FormattingService
    {
        public string AsReadableDate(DateTime date)
        {
            return date.ToString("D");
        }
    }
}

Ex_Files_ASPNET_CoreMVC/Ex_Files_ASPNET_CoreMVC/Exercise Files/Ch03/03_08_End/src/ExploreCalifornia/Models/Post.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExploreCalifornia.Models
{
    public class Post
    {
        public string Title { get; set; }
        public string Author { get; set; }
        public string Body { get; set; }
        public DateTime Posted { get; set; }
    }
}

Ex_Files_ASPNET_CoreMVC/Ex_Files_ASPNET_CoreMVC/Exercise Files/Ch03/03_08_End/src/ExploreCalifornia/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ExploreCalifornia.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace ExploreCalifornia.Controllers
{
    [Route("blog")]
    public class BlogController : Controller
    {
        [Route("")]
        public IActionResult Index()
        {
            var posts = new[]
            {
                new Post
                {
                    Title = "My blog post",
                    Posted = DateTime.Now,
                    Author = "Jess Chadwick",
                    Body = "This is a great blog post, don't you think?",
                },
                new Post
                {
                    Title = "My second blog post",
                    Posted = DateTime.Now,
                    Author = "Jess Chadwick",
                    Body = "This is ANOTHER great blog post, don't you think?",
                },
            };

            return View(posts);
        }

        [Route("{year:min(2000)}/{month:range(1,12)}/{key}")]
        public IActionResult Post(int year, int month, string key)
        {
            var post = new Post
            {
                Title = "My blog post",
                Posted = DateTime.Now,
                Author = "Jess Chadwick",
                Body = "This is a great blog post, don't you think?",
            };

            return View(post);
        }
    }
}

Ex_Files_ASPNET_CoreMVC/Ex_Files_ASPNET_CoreMVC/Exercise Files/Ch03/03_08_End/src/ExploreCalifornia/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace ExploreCalifornia.Controllers
{
    public class HomeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

Ex_Files_ASPNET_CoreMVC/Ex_Files_ASPNET_CoreMVC/Exercise Files/Ch03/03_08_End/src/ExploreCalifornia/ViewComponents/MonthlySpecialsViewComponent.cs
using ExploreCalifornia.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExploreCalifornia.ViewComponents
{
    [ViewComponent]
    public class MonthlySpecialsViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }

    }
}

Ex_Files_ASPNET_CoreMVC/Ex_Files_ASPNET_CoreMVC/Exercise Files/Ch03/03_08_End/src/ExploreCalifornia/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Welcome to Explore California</title>
<meta name="description" content="A lynda.com example of HTML5 and CSS3">
<meta name="keywords" content="html5, css3, lynda, local storage, canvas, forms, semantics, web apps">
<!--make sure mobile devices display the page at the proper scale	-->
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<link href="/css/main.css" rel="stylesheet" type="text/css" media="screen, projection">
</head>
<body id="home" class="no-js">
<div id="wrapper">
  <header id="mainHeader"> <a href="/" title="home" class="logo">
   <!-- I need this div because IE is an affront to mankind-->
    <div>
    <h1>Explore California</h1>
    </div>
    </a>
    <nav id="siteNav">
      <h1>Where do you want to go?</h1>
      <ul>
       <li><a href="/tours.htm" title="Our tours">Tours <br /><span class="tagline">follow our bliss</span></a>
          <ul>
            <li><a href="/tours.htm" title="Our tours">All Tours</a></li>
            <li><a href="/tours.htm" title="find tours">Tours by Activity</a></li>
            <li><a href="/tours.htm" title="find tours">Tours by Region</a></li>
            <li><a href="/tours.htm" title="find tours">Tour Finder</a></li>
          </ul>
        </li>
        <li><a href="mission.htm" title="What we believe">Mission <br /><span class="tagline">what makes us different?</span></a></li>
        <li><a href="resources.htm" title="planning resources">Resources <br /><span class="tagline">plan your trip</span></a>
          <ul>
            <li><a href="resources/faq.htm" title="Got questions?">Tour FAQs</a></li>
            <li><a href="resources/additional_resources.htm" title="additional resources">Tour Information</a></li>
            <li><a href="resources/terms.htm" title="terms and conditions">Site Terms</a></li>
          </ul>
        </li>
        <li><a href="explorers.htm" title="Our community">Explorers <br /><span class="tagline">join our community</span></a>
          <ul>
            <li><a href="explorers/join.htm" title="join our community">Join the Explorers</a></li>
            <li><a href="@Url.Action("Index", "Blog")" title="read our blog!">Read our Blog</a></li>
            <li><a href="explorers/gallery.htm" title="contributor photos">Tour Photos</a></li>
            <li><a href="_video/EC_podcast_full version.mov" title="check out our podcast">Video podcast</a></li>
          </ul>
        </li>
        <li><a href="contact.htm" title="contact us" class="last">Contact <br /><span class="tagline">we're listening</span></a>
          <ul>
            <li><a href="support.htm" title="need help?">Support</a></li>
          </ul>
        </li>
      </ul>
    </nav>
  </header>
  <section id="actionCall">
      @if (IsSectionDefined("header"))
      {
        @RenderSection("header", false)
      } else
      {
          <h1>Explore our world your way</h1>
      }
  </section>
  <div id="contentWrapper">
  <section id="mainContent">
    @RenderBody()
  </section>
    <aside id="secondaryContent">
        <div id="specials" class="callOut">
            @await (Component.InvokeAsync<ExploreCalifornia.ViewComponents.MonthlySpecialsViewComponent>())
        </div>
        <div id="trivia" class="callOut">
            <h1>Did You Know?</h1>
            <p>California produces over 17 million gallons of wine each year!</p>
        </div>
    </aside>
  </div>
  <footer id="pageFooter">
  <section id="quickLinks">
  <h1>Quick Nav</h1>
    <ul id="quickNav">
      <li><a href="/" title="Our home page">Home</a></li>
      <li><a href="/tours.htm" title="Explore our tours">Tours</a></li>
      <li><a href="mission.htm" title="What we think">Mission</a></li>
      <li><a href="resources.htm" title="Guidance and planning">Resources</a></li>
      <li><a href="explorers.htm" title="Join our community">Explorers</a></li>
      <li><a href="contact.htm" title="Contact and support">Contact</a></li>
    </ul>
  </section>
  <section id="footerResources">
  <h1>Resources</h1>
    <ul id="quickNav">
      <li><a href="resources/faq.htm" title="Our home page">FAQ</a></li>
      <li><a href="support.htm" title="Need help?">Support</a></li>
      <li><a href="resources/legal.htm" title="The fine print">Legal</a></li><li><a href="login.htm">Login</a></li>
    </ul>

      <p>
          Copyright Jess Chadwick @DateTime.Now.Year
      </p>
  </section>
  <section id="companyInfo">
  <h1>Contact</h1>
  <h2>Explore California</h2>
      <p>5605 Nota Street<br />
        Ventura, CA 93003</p>
      <p>866.555.4310<br />866.555.4315 <em>(24 hour support)</em></p>
  </section>
  </footer>
</div>
</body>
</html>

Ex_Files_ASPNET_CoreMVC/Ex_Files_ASPNET_CoreMVC/Exercise Files/Ch03/03_08_End/src/ExploreCalifornia/Views/Shared/_Post.cshtml
@inject ExploreCalifornia.Models.FormattingService Format
@model ExploreCalifornia.Models.Post

<article class="blog-post">
    <h1>@Model.Title</h1>
    <div class="details">
        Posted <span>@Format.AsReadableDate(Model.Posted)</span> by <span>@Model.Author</span>
    </div>
    <div class="content">
        @Model.Body
    </div>
</article>